#%RAML 0.8
#revision: 1
baseUri: http://jmetzz.github.com
title: Sales RAML
version: 1.0

schemas:
    - createOrder:                          !include schemas/createOrder.json
    - modifyOrder:                          !include schemas/modifyOrder.json
    - getOrder:                             !include schemas/getOrder.json
    - searchOrders:                         !include schemas/searchOrders.json
    - addOrderLine:                         !include schemas/addOrderLine.json
    - modifyOrderLine:                      !include schemas/modifyOrderLine.json
    - getOrderLines:                        !include schemas/getOrderLines.json
    - getOrderLine:                         !include schemas/getOrderLine.json


/sales:
  /orders:
    get:
      description: Search sales orders
      queryParameters:
        size:
          type: integer
          description: The number of items to be returned
          example: ?size=10
          required: false
        page:
          type: integer
          description: The page to be returned
          example: ?page=1
          required: false
        customerID:
          type: string
          description: The unique ID of the customer
          example: ?customerID=8521
          required: false
        productID:
          type: string
          description: The unique ID of the product.
          example: ?productID=148
          required: false
      responses:
        200:
          body:
            application/json:
              schema: searchOrders
              example: !include samples/searchOrders.json
  /order:
    post:
      description: Create a new sales order
      body:
        application/json:
          schema: createOrder
          example: !include samples/createOrder.json
      responses:
        201:
          headers:
            location:
              required: true
              description: Location of the new resource
              example: /sales/order/{salesID}

    /{orderID}:
      uriParameters:
        orderID:
      put:
        description: Updates a sales order
        body:
          application/json:
            schema: modifyOrder
            example: !include samples/modifyOrder.json
        responses:
          204:
            headers:
              location:
                required: true
                description: Location of the updated resource
                example: /sales/order/{orderID}
      get:
        description: Get a sales order by ID
        queryParameters:
           fetchOrderLines:
              description: fetch the associated order lines?
              type: boolean
              required: false
              example: true
        responses:
          200:
            body:
              application/json:
                schema: getOrder
                example: !include samples/getOrder.json

      /submit:
        post:
          description: Performs the business operation submit.
          responses:
            200:

      /copy:
        post:
          description: Copies this order and the order lines.
          responses:
            201:
              headers:
                location:
                  required: true
                  description: Location of the new resource
                  example: /sales/order/{orderID}

      /accept:
        post:
          description: Performs the business operation accept.
          responses:
            200:


      /delete:
        post:
          description: Performs the business operation delete.
          responses:
            200:

      /line:
        post:
          description: Create a new line for an order
          body:
            application/json:
              schema: addOrderLine
              example: !include samples/addOrderLine.json

          responses:
            201:
              headers:
                location:
                  required: true
                  description: Location of the created order line
                  example: /sales/order/{orderID}/line/{orderLineID}

        /{orderLineID}:
            uriParameters:
              orderLineID:
            put:
              description: Updates an existing line for an order
              body:
                application/json:
                  schema: modifyOrderLine
                  example: !include samples/modifyOrderLine.json
              responses:
                204:
                  headers:
                    location:
                      required: true
                      description: Location of the updated resource
                      example: /sales/order/{orderID}/line/{orderLineID}

            get:
              description: Gets an existing order line
              responses:
                200:
                  body:
                    application/json:
                      schema: getOrderLine
                      example: !include samples/getOrderLine.json

            /delete:
              post:
                description: Deletes a sales order line
                responses:
                  200: